# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: [".env"]

tasks:
  # -------------------------
  # deps
  # -------------------------

  deps:
    desc: tidy go modules
    cmds:
      - go mod tidy

  # -------------------------
  # formatting / lint
  # -------------------------

  fmt:
    desc: format code
    cmds:
      - go fmt ./...

  lint:
    desc: run golangci-lint
    cmds:
      - golangci-lint run

  # -------------------------
  # tests
  # -------------------------

  test:
    desc: run tests
    cmds:
      - go test ./...
